---
apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: "2024-10-30T21:01:41Z"
    labels:
      operator.openshift.io/controller-instance-name: oauth-apiserver-RevisionController
    name: audit-1
    namespace: openshift-oauth-apiserver
    ownerReferences:
    - apiVersion: v1
      kind: ConfigMap
      name: revision-status-1
      uid: 71b57f1f-a53e-46ce-aebf-272a5d2b3c02
    resourceVersion: "7246"
    uid: f6ed0639-913c-4322-a1a1-4b8d48dbc8ae
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      operator.openshift.io/revision-ready: "true"
    creationTimestamp: "2024-10-30T21:01:38Z"
    labels:
      operator.openshift.io/controller-instance-name: oauth-apiserver-RevisionController
    name: revision-status-1
    namespace: openshift-oauth-apiserver
    resourceVersion: "7568"
    uid: 71b57f1f-a53e-46ce-aebf-272a5d2b3c02
kind: ConfigMapList
